services:
  postgres:
    image: bitnami/postgresql
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=curtin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d curtin -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - curtin:/bitnami/postgresql
volumes:
  curtin: